// <auto-generated />
namespace RubricMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addoldfacetid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addoldfacetid));
        
        string IMigrationMetadata.Id
        {
            get { return "202205070304351_Add old facet id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
