// <auto-generated />
namespace RubricMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addIsCreatingfieldtofacetmodelview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addIsCreatingfieldtofacetmodelview));
        
        string IMigrationMetadata.Id
        {
            get { return "202205090121056_add IsCreating field to facet model view"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
