// <auto-generated />
namespace RubricMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addrubrictofacetModelView : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addrubrictofacetModelView));
        
        string IMigrationMetadata.Id
        {
            get { return "202205052101138_add rubric to facetModelView"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
